<?php

namespace Tests;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\URL;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    use WithFaker;
    use DatabaseTransactions;

    private $images;

    public function fakeImageStream($width = 300, $height = 300, $extension = 'jpeg')
    {
        $tmp = tmpfile();

        $imagick = new \Imagick();
        $imagick->newImage($width, $height, new \ImagickPixel('white'));
        $imagick->addNoiseImage(\Imagick::NOISE_RANDOM, \Imagick::CHANNEL_DEFAULT);
        $imagick->setImageFormat($extension);

        fwrite($tmp, $imagick->getImageBlob());

        $key = uniqid();

        $this->images[$key] = $tmp;

        return stream_get_meta_data($this->images[$key])['uri'];
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        // setting routes locale by default so that the use of route doesn't break down
        URL::defaults(['locale' => config('app.locale')]);
    }
}
